title: "王小帅的博客"
email: "903603746@qq.com"
description: > # this means to ignore newlines until "baseurl:"
  too shuai
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://18667931421.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  18667931421
